// import localFont from "next/font/local";
'use client'
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css"
import Panel from "@/components/panel";
// import Fallback from "@/components/fallback";
import { useState} from "react";
import Image from "next/image";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Home - metal calculation",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const HomeMenu = [
    {
      id: 0,
      icon: '/image/hexagon.png',
      name: 'Hexagon',
      link: '/hexagon'
    },
    {
      id: 1,
      icon: '/image/hexagon.png',
      name: 'Round Bar',
      link: '/round-bar'
    },
    {
      id: 2,
      icon: '/image/hexagon.png',
      name: 'Round Tube',
      link: '/round-tube'
    },
    {
      id: 3,
      icon: '/image/hexagon.png',
      name: 'Square Bar',
      link: '/square-bar'
    },
    {
      id: 4,
      icon: '/image/hexagon.png',
      name: 'Square Tube',
      link: '/square-tube'
    },
    {
      id: 5,
      icon: '/image/hexagon.png',
      name: 'T Bar',
      link: '/t-bar'
    },
    {
      id: 6,
      icon: '/image/hexagon.png',
      name: 'Beams',
      link: '/beams'
    },
    {
      id: 7,
      icon: '/image/hexagon.png',
      name: 'Channel',
      link: '/channel'
    },
    {
      id: 8,
      icon: '/image/hexagon.png',
      name: 'Angle',
      link: '/angle'
    },
    {
      id: 9,
      icon: '/image/hexagon.png',
      name: 'Flat Bar',
      link: '/flat-bar'
    },
    {
      id: 10,
      icon: '/image/hexagon.png',
      name: 'Sheet',
      link: '/sheet'
    }
  ]

  const [items, setItems] = useState(HomeMenu);

  //  const DataContext = createContext()

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <div className="flex bg-primary justify-between p-4 sticky top-0 z-50">
            {/* <Image src={} height={40} width={40} alt="logo" /> */}
            <div>
             <p className="text-lg text-white font-semibold">Iftekher mahmud pervez</p> 
            </div>
          </div>

          <main>

            <div className="lg:grid grid-cols-5 gap-2 p-2 py-4">
              <div>
                <Panel items={items} />
              </div>
              <div className="col-span-4">
                <div className="bg-neutral p-4 rounded-lg min-h-screen">
                  {/* <DataContext.Provider value={items}> */}
                  {/* <Suspense fallback={<Fallback/>}> */}
                    {children}
                  {/* </Suspense> */}
                  
                  {/* </DataContext.Provider>  */}
                </div>
              </div>
            </div>


          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap bg-black items-center justify-center">

          </footer>
        </div>

      </body>
    </html>
  );
}
