// import localFont from "next/font/local";
'use client'
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css"
import Panel from "@/components/panel";
import Image from "next/image";
import { useState} from "react";
// import Image from "next/image";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Home - metal calculation",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const HomeMenu = [
    {
      id: 0,
      icon: '/image/hexagon.png',
      name: 'Hexagon',
      link: '/hexagon'
    },
    {
      id: 1,
      icon: '/image/hexagon.png',
      name: 'Round Bar',
      link: '/round-bar'
    },
    {
      id: 2,
      icon: '/image/hexagon.png',
      name: 'Round Tube',
      link: '/round-tube'
    },
    {
      id: 3,
      icon: '/image/hexagon.png',
      name: 'Square Bar',
      link: '/square-bar'
    },
    {
      id: 4,
      icon: '/image/hexagon.png',
      name: 'Square Tube',
      link: '/square-tube'
    },
    {
      id: 5,
      icon: '/image/hexagon.png',
      name: 'T Bar',
      link: '/t-bar'
    },
    {
      id: 6,
      icon: '/image/hexagon.png',
      name: 'Beams',
      link: '/beams'
    },
    {
      id: 7,
      icon: '/image/hexagon.png',
      name: 'Channel',
      link: '/channel'
    },
    {
      id: 8,
      icon: '/image/hexagon.png',
      name: 'Angle',
      link: '/angle'
    },
    {
      id: 9,
      icon: '/image/hexagon.png',
      name: 'Flat Bar',
      link: '/flat-bar'
    },
    {
      id: 10,
      icon: '/image/hexagon.png',
      name: 'Sheet',
      link: '/sheet'
    }
  ]

  const [items, setItems] = useState(HomeMenu);

  //  const DataContext = createContext()

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <div className="flex bg-primary justify-between p-4 sticky top-0 z-50">
            {/* <Image src={} height={40} width={40} alt="logo" /> */}
            <div>
              <p className="text-lg text-white font-semibold">Iftekher mahmud pervez</p>
            </div>
            <div>
              <div className="drawer-content">
                {/* Page content here */}
                <label htmlFor="my-drawer-4" className="drawer-button btn btn-neutral">About</label>
              </div>
            </div>
            
          </div>

          <main>

          <div className="drawer drawer-end z-50">
              <input id="my-drawer-4" type="checkbox" className="drawer-toggle" />
              <div className="drawer-side">
                <label htmlFor="my-drawer-4" aria-label="close sidebar" className="drawer-overlay"></label>
                <ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4">
                  {/* Sidebar content here */}

                <div className="flex flex-col justify-center items-center p-2 gap-2">
                    <Image src={'/image/avatar.jpg'} className="rounded-full" height={100} width={100} alt="Creator Avatar" />
                  
                  <div>
                    <h3 className="text-lg uppercase font-bold">Iftekher Mahmud Pervez</h3>
                  </div>

                </div>

                  
                </ul>
              </div>
            </div>

            <div className="lg:grid grid-cols-5 gap-2 p-2 py-4">
              <div>
                <Panel items={items} />
              </div>
              <div className="col-span-4">
                <div className="bg-neutral p-4 rounded-lg min-h-screen">
                  {/* <DataContext.Provider value={items}> */}
                  {children}
                  {/* </DataContext.Provider>  */}
                </div>
              </div>
            </div>


          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap bg-black items-center justify-center">

          </footer>
        </div>

      </body>
    </html>
  );
}
